// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.9
// source: mtgsim.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActionType represents the type of an action a player can take.
type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_PASS_PRIORITY           ActionType = 1
	ActionType_CAST_SPELL              ActionType = 2
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "PASS_PRIORITY",
		2: "CAST_SPELL",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"PASS_PRIORITY":           1,
		"CAST_SPELL":              2,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_mtgsim_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_mtgsim_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_mtgsim_proto_rawDescGZIP(), []int{0}
}

// Action represents a single action that a player can perform.
// This is what a client would send to the server.
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ActionType `protobuf:"varint,1,opt,name=type,proto3,enum=mtgsim.ActionType" json:"type,omitempty"`
	// The payload will vary based on the action type.
	//
	// Types that are assignable to Payload:
	//
	//	*Action_CastSpell
	Payload isAction_Payload `protobuf_oneof:"payload"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtgsim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_mtgsim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_mtgsim_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (m *Action) GetPayload() isAction_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Action) GetCastSpell() *CastSpellPayload {
	if x, ok := x.GetPayload().(*Action_CastSpell); ok {
		return x.CastSpell
	}
	return nil
}

type isAction_Payload interface {
	isAction_Payload()
}

type Action_CastSpell struct {
	CastSpell *CastSpellPayload `protobuf:"bytes,2,opt,name=cast_spell,json=castSpell,proto3,oneof"`
}

func (*Action_CastSpell) isAction_Payload() {}

// Payload for casting a spell.
type CastSpellPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId  string   `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"` // UUIDs are represented as strings
	Targets []string `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *CastSpellPayload) Reset() {
	*x = CastSpellPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtgsim_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastSpellPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSpellPayload) ProtoMessage() {}

func (x *CastSpellPayload) ProtoReflect() protoreflect.Message {
	mi := &file_mtgsim_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSpellPayload.ProtoReflect.Descriptor instead.
func (*CastSpellPayload) Descriptor() ([]byte, []int) {
	return file_mtgsim_proto_rawDescGZIP(), []int{1}
}

func (x *CastSpellPayload) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CastSpellPayload) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

var File_mtgsim_proto protoreflect.FileDescriptor

var file_mtgsim_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x74, 0x67, 0x73, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6d, 0x74, 0x67, 0x73, 0x69, 0x6d, 0x22, 0x76, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x6d, 0x74, 0x67, 0x73, 0x69, 0x6d, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x61, 0x73, 0x74,
	0x5f, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d,
	0x74, 0x67, 0x73, 0x69, 0x6d, 0x2e, 0x43, 0x61, 0x73, 0x74, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x09, 0x63, 0x61, 0x73, 0x74, 0x53, 0x70,
	0x65, 0x6c, 0x6c, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x45,
	0x0a, 0x10, 0x43, 0x61, 0x73, 0x74, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x73, 0x2a, 0x4c, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x50, 0x41, 0x53, 0x53, 0x5f, 0x50, 0x52, 0x49, 0x4f, 0x52, 0x49, 0x54,
	0x59, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x41, 0x53, 0x54, 0x5f, 0x53, 0x50, 0x45, 0x4c,
	0x4c, 0x10, 0x02, 0x32, 0x08, 0x0a, 0x06, 0x4d, 0x74, 0x67, 0x53, 0x69, 0x6d, 0x42, 0x10, 0x5a,
	0x0e, 0x6d, 0x74, 0x67, 0x73, 0x69, 0x6d, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mtgsim_proto_rawDescOnce sync.Once
	file_mtgsim_proto_rawDescData = file_mtgsim_proto_rawDesc
)

func file_mtgsim_proto_rawDescGZIP() []byte {
	file_mtgsim_proto_rawDescOnce.Do(func() {
		file_mtgsim_proto_rawDescData = protoimpl.X.CompressGZIP(file_mtgsim_proto_rawDescData)
	})
	return file_mtgsim_proto_rawDescData
}

var file_mtgsim_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mtgsim_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mtgsim_proto_goTypes = []interface{}{
	(ActionType)(0),          // 0: mtgsim.ActionType
	(*Action)(nil),           // 1: mtgsim.Action
	(*CastSpellPayload)(nil), // 2: mtgsim.CastSpellPayload
}
var file_mtgsim_proto_depIdxs = []int32{
	0, // 0: mtgsim.Action.type:type_name -> mtgsim.ActionType
	2, // 1: mtgsim.Action.cast_spell:type_name -> mtgsim.CastSpellPayload
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mtgsim_proto_init() }
func file_mtgsim_proto_init() {
	if File_mtgsim_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mtgsim_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtgsim_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastSpellPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mtgsim_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Action_CastSpell)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mtgsim_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mtgsim_proto_goTypes,
		DependencyIndexes: file_mtgsim_proto_depIdxs,
		EnumInfos:         file_mtgsim_proto_enumTypes,
		MessageInfos:      file_mtgsim_proto_msgTypes,
	}.Build()
	File_mtgsim_proto = out.File
	file_mtgsim_proto_rawDesc = nil
	file_mtgsim_proto_goTypes = nil
	file_mtgsim_proto_depIdxs = nil
}
