// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.9
// source: mtgsim.proto

package api

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MtgSimClient is the client API for MtgSim service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MtgSimClient interface {
}

type mtgSimClient struct {
	cc grpc.ClientConnInterface
}

func NewMtgSimClient(cc grpc.ClientConnInterface) MtgSimClient {
	return &mtgSimClient{cc}
}

// MtgSimServer is the server API for MtgSim service.
// All implementations must embed UnimplementedMtgSimServer
// for forward compatibility
type MtgSimServer interface {
	mustEmbedUnimplementedMtgSimServer()
}

// UnimplementedMtgSimServer must be embedded to have forward compatible implementations.
type UnimplementedMtgSimServer struct {
}

func (UnimplementedMtgSimServer) mustEmbedUnimplementedMtgSimServer() {}

// UnsafeMtgSimServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MtgSimServer will
// result in compilation errors.
type UnsafeMtgSimServer interface {
	mustEmbedUnimplementedMtgSimServer()
}

func RegisterMtgSimServer(s grpc.ServiceRegistrar, srv MtgSimServer) {
	s.RegisterService(&MtgSim_ServiceDesc, srv)
}

// MtgSim_ServiceDesc is the grpc.ServiceDesc for MtgSim service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MtgSim_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mtgsim.MtgSim",
	HandlerType: (*MtgSimServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "mtgsim.proto",
}
